### ISSUE TITLE
Question about Chapter 5

### ISSUE THREAD

**Issue by imjcham** [PacktPublishing/Building-Machine-Learning-Projects-with-TensorFlow#1]
Great book, I've been following the examples.  I'm new to ML so excuse my questions if they are silly.

1.  In your quadratic example in chapter 5, the following line for dsY, I believe should not have the zero in front of it.  
`testX, testY = dsX[trainsamples:trainsamples + testsamples], dsY[0:trainsamples:trainsamples+testsamples]`

2.  I noticed that you called one of your notebooks CH5 linear regression nn (neural network).  However, in the actual chapter, it's called Non linear synthetic function regression.  I'm sort of confused. Can you explain why you are calling it linear here and non-linear in the actual book?

**Comment by rnditdev** [comment]
Hello,
First, thanks for the compliments!
I'm beginning to answer questions and update the examples based on feedback. Please allow me some days to work on your requests. Feel free to ask more questions in the meantime.

Best Regards,
Ing. Rodolfo Bonnin.

**Comment by dbmlabs** [comment]
Sure.  Also, Chapter 5, second example, the skflow package has been replaced with learn and there are some issues when running the notebook with skflow.  Let me know if you are able to run the code with the latest version of tensorflow (0.12)

**Comment by dbmlabs** [comment]
Hello, I was going through chapter 7, the github is missing the code for the "writing music "a la" Bach" example.

**Comment by rnditdev** [comment]
Chapte 7 example is added.

**Comment by imjcham** [comment]
How come this was closed without a real answer to the questions?

**Comment by techsachinkumar** [comment]
Hi @imjcham 

I checked to see that author had updated all the codes in the repository.
Author has also added chapter 7 missing codes as his mentioned reply above and hence i closed it. 
Please have a look at the updated codes and let us know if you are facing any issue.
You can reopen this thread or may open a new log for the same.

Regards.
