### ISSUE TITLE
Readme hyperlink issue

### ISSUE THREAD

**Issue by skjha1** [PacktPublishing/Building-Machine-Learning-Projects-with-TensorFlow#19]
[None of the link is working](https://github.com/PacktPublishing/Building-Machine-Learning-Projects-with-TensorFlow#building-machine-learning-projects-with-tensorflow)

**Comment by ManikandanKurup-Packt** [comment]
Hi @skjha1 

Thank you for letting us know. We have updated all the links in the README file.
