### ISSUE TITLE
Question about Chapter 7

### ISSUE THREAD

**Issue by yogpatel** [PacktPublishing/Building-Machine-Learning-Projects-with-TensorFlow#2]
Hi,

I have couple of question on Chapter 7:

1. In Example 1 - univariate time series prediction with energy consumption data - when I run the example I get an error stating: AttributeError: module 'tensorflow.contrib.learn' has no attribute 'TensorFlowEstimator. Googling the problem I found tensflow have removed TensorFlowEstimator. What is the alternative for this?

2. No code supplied for the Example 2 on the github.

**Comment by rnditdev** [comment]
Hello,
The Tensorflow has suffered many alterations since the book launch, the task of updating some samples will need at least a new book edition.

I'll be looking into the issue of missing Example 2.

Thank you and best regards.

**Comment by rnditdev** [comment]
The code us updated for recent version of Tensorflow.

**Comment by sebst** [comment]
Looks like CH7_time_series.py is still not updated.
