### ISSUE TITLE
question about chapter 3

### ISSUE THREAD

**Issue by leonardgithub** [PacktPublishing/Building-Machine-Learning-Projects-with-TensorFlow#9]
in Multivariate Linear Regression.py, it will not show the plot until I add one line:
plot.show()
Could you tell me why?

**Comment by wangdxh** [comment]
default the plot‘s interactive mode is off， in console mode is on
can change by  ioff  ion， in ioff mode must call show（）。

**Comment by shubham763** [comment]
Please reopen if the issue still persists.
